// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// ConfigKeyFishpi is a ConfigKey of type fishpi.
	// 摸鱼派
	ConfigKeyFishpi ConfigKey = "fishpi"
)

var ErrInvalidConfigKey = fmt.Errorf("not a valid ConfigKey, try [%s]", strings.Join(_ConfigKeyNames, ", "))

var _ConfigKeyNames = []string{
	string(ConfigKeyFishpi),
}

// ConfigKeyNames returns a list of possible string values of ConfigKey.
func ConfigKeyNames() []string {
	tmp := make([]string, len(_ConfigKeyNames))
	copy(tmp, _ConfigKeyNames)
	return tmp
}

// ConfigKeyValues returns a list of the values for ConfigKey
func ConfigKeyValues() []ConfigKey {
	return []ConfigKey{
		ConfigKeyFishpi,
	}
}

// String implements the Stringer interface.
func (x ConfigKey) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigKey) IsValid() bool {
	_, err := ParseConfigKey(string(x))
	return err == nil
}

var _ConfigKeyValue = map[string]ConfigKey{
	"fishpi": ConfigKeyFishpi,
}

// ParseConfigKey attempts to convert a string to a ConfigKey.
func ParseConfigKey(name string) (ConfigKey, error) {
	if x, ok := _ConfigKeyValue[name]; ok {
		return x, nil
	}
	return ConfigKey(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigKey)
}

// MustParseConfigKey converts a string to a ConfigKey, and panics if is not valid.
func MustParseConfigKey(name string) ConfigKey {
	val, err := ParseConfigKey(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ConfigKey) Ptr() *ConfigKey {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ConfigKey) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigKey) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigKey(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
